version: '3.9'
services:
  frontend:
    container_name: app_frontend
    build: ./front-end
    ports:
      - 3000:3000
    platform: linux/x86_64
    working_dir: /frontend
    volumes:
      - ./front-end/src:/frontend/src
    depends_on:
      - backend
  dulcinha-totem:
    container_name: app_dulcinha
    build: ./dulcinha-totem
    ports:
      - 3002:3002
    platform: linux/x86_64
    working_dir: /dulcinha
    volumes:
      - ./dulcinha-totem/src:/dulcinha/src
    depends_on:
      - backend
  backend:
    container_name: app_backend
    build: ./back-end
    ports:
      - 3001:3001
    platform: linux/x86_64
    working_dir: /backend
    command: dev
    volumes:
      - ./back-end/src:/backend/src
    depends_on:
      - db
    environment:
      - APP_PORT=3001
      - JWT_SECRET=jwt_secret
      # Os dados abaixo se referem ao container `db`
      - NODE_ENV=development
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
  db:
    image: mysql:8.0.21
    container_name: db
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
    cap_add:
      - SYS_NICE # Deve omitir alertas menores
